const knownAssetType = new Map<string, string>();
knownAssetType.set("Microsoft.Web/sites", "Web Apps");
knownAssetType.set("Microsoft.Web/serverFarms", "App Service Plans");
knownAssetType.set("Microsoft.Web/sites/slots", "Deployment Slots");
knownAssetType.set("Microsoft.Web/certificates", "Certificates");
knownAssetType.set("Microsoft.DocumentDB/databaseAccounts", "Cosmos DBs");
knownAssetType.set("Microsoft.AlertsManagement/", "Alert Rules");
knownAssetType.set("Microsoft.Portal/dashboards", "Portal Dashboards");
knownAssetType.set("Microsoft.Insights/", "Insights Components");
knownAssetType.set("Microsoft.Network/routeTables", "Route Tables");
knownAssetType.set("Microsoft.Network/frontdoor", "Frontdoors");
knownAssetType.set("Microsoft.Network/networkSecurityGroups", "Network Security Groups");
knownAssetType.set("Microsoft.Network/serviceEndpointPolicies", "Service Endpoint Policies");
knownAssetType.set("Microsoft.Network/virtualNetworks", "Virtual Networks");
knownAssetType.set("Microsoft.Network/publicIPAddresses", "Public IPs");
knownAssetType.set("Microsoft.Storage/storageAccounts", "Storage Accounts");
knownAssetType.set("Microsoft.KeyVault/vaults", "KeyVaults");
knownAssetType.set("Microsoft.Cdn/profiles", "CDN Profiles");
knownAssetType.set("Microsoft.Cdn/profiles/afdendpoints", "Front Door CDN Endpoints");
knownAssetType.set("Microsoft.ServiceBus/namespaces", "Service Bus Namespaces");
knownAssetType.set("Microsoft.SaaS/resources", "SaaS Resources");
knownAssetType.set("Microsoft.AppConfiguration/configurationStores", "Configuration Stores");
knownAssetType.set("Microsoft.ManagedIdentity/userAssignedIdentities", "User Assigned Identities");
knownAssetType.set("Microsoft.Sql/servers", "MsSQL Server Databases");
knownAssetType.set("Microsoft.Databricks/workspaces", "Databrick Workspaces");
knownAssetType.set("Microsoft.DataFactory/factories", "DataFactories");
knownAssetType.set("Microsoft.EventGrid/systemTopics", "EventGrid System Topics");
knownAssetType.set("Microsoft.EventGrid/topics", "EventGrid topics");
knownAssetType.set("Microsoft.Cache/Redis", "Redis Caches");
knownAssetType.set("Microsoft.Batch/batchAccounts", "Microsoft Batch");
knownAssetType.set("Microsoft.OperationalInsights/workspaces", "Operational Insights Workspaces");
knownAssetType.set("Microsoft.Network/trafficmanagerprofiles", "Traffic Manager Profiles");

const assetTypeGlyphs = new Map<string, string>();
assetTypeGlyphs.set("Microsoft.Web/sites", "fas fa-globe");
assetTypeGlyphs.set("Microsoft.Web/serverFarms", "fas fa-server");
assetTypeGlyphs.set("Microsoft.Web/sites/slots", "fas fa-code-branch");
assetTypeGlyphs.set("Microsoft.Web/certificates", "fas fa-certificate");
assetTypeGlyphs.set("Microsoft.DocumentDB/databaseAccounts", "fas fa-database");
assetTypeGlyphs.set("Microsoft.AlertsManagement/", "fas fa-bell");
assetTypeGlyphs.set("Microsoft.Portal/dashboards", "fas fa-desktop");
assetTypeGlyphs.set("Microsoft.Insights/", "fas fa-chart-line");
assetTypeGlyphs.set("Microsoft.Storage/storageAccounts", "fas fa-hdd");
assetTypeGlyphs.set("Microsoft.KeyVault/vaults", "fas fa-key");
assetTypeGlyphs.set("Microsoft.Cdn/profiles", "fas fa-cloud");
assetTypeGlyphs.set("Microsoft.Cdn/profiles/afdendpoints", "fas fa-door-open");
assetTypeGlyphs.set("Microsoft.ServiceBus/namespaces", "fas fa-stream");
assetTypeGlyphs.set("Microsoft.SaaS/resources", "fas fa-cloud");
assetTypeGlyphs.set("Microsoft.AppConfiguration/configurationStores", "fas fa-cogs");
assetTypeGlyphs.set("Microsoft.ManagedIdentity/userAssignedIdentities", "fas fa-user-secret");
assetTypeGlyphs.set("Microsoft.Sql/servers", "fas fa-database");
assetTypeGlyphs.set("Microsoft.Databricks/workspaces", "fas fa-code");
assetTypeGlyphs.set("Microsoft.DataFactory/factories", "fas fa-cogs");
assetTypeGlyphs.set("Microsoft.EventGrid/topics", "fas fa-stream");
assetTypeGlyphs.set("Microsoft.EventGrid/systemTopics", "fas fa-stream");
assetTypeGlyphs.set("Microsoft.Cache/Redis", "fas fa-server");
assetTypeGlyphs.set("Microsoft.Batch/batchAccounts", "fas fa-terminal");
assetTypeGlyphs.set("Microsoft.OperationalInsights/workspaces", "fas fa-file");
assetTypeGlyphs.set("Microsoft.Network/routeTables", "fas fa-sitemap");
assetTypeGlyphs.set("Microsoft.Network/frontdoor", "fas fa-network-wired");
assetTypeGlyphs.set("Microsoft.Network/networkSecurityGroups", "fas fa-user-secret");
assetTypeGlyphs.set("Microsoft.Network/serviceEndpointPolicies", "fas fa-network-wired");
assetTypeGlyphs.set("Microsoft.Network/virtualNetworks", "fas fa-network-wired");
assetTypeGlyphs.set("Microsoft.Network/publicIPAddresses", "fas fa-ethernet");
assetTypeGlyphs.set("Microsoft.Network/trafficmanagerprofiles", "fas fa-network-wired");

export {    
    knownAssetType,
    assetTypeGlyphs
}